name: On Commit Build & Test Hook - Client Library

on: [push]

jobs:
  build:
    env:
      buildDir: '${{ github.workspace }}/build/'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        python-version: [3.8]
        os: [windows-latest]
        include:
        - os: windows-latest
          build-triplet: x64-windows

    steps:
    - name: Get Repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v6
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      with:
        setupOnly: true
        vcpkgGitCommitId: 9172179c513aa84308e48b8dd0e3df90acec7204
        vcpkgTriplet: ${{ matrix.build-triplet }}
        additionalCachedPaths: ${{ github.workspace }}/clients/cpp/vcpkg_installed
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

    - name: Install dependencies VCPKG
      run: |
        $VCPKG_ROOT/vcpkg install  --x-install-root=./vcpkg_installed --triplet=${{ matrix.build-triplet }} --overlay-triplets=./triplet-overlays/
      shell: bash
